#pragma once

#define this_ptr shared_from_this()

#include "GRAPHIC/jeGraphic.h"
#include "GRAPHIC/jeImage.h"
#include "GRAPHIC/jeKeyframe.h"
#include "GRAPHIC/jeModel.h"
#include "GRAPHIC/jeParticle.h"
#include "GRAPHIC/jeProgram.h"
#include "GRAPHIC/jeShader.h"
#include "GRAPHIC/jeSpritemap.h"
#include "GRAPHIC/jeTilemap.h"
#include "GRAPHIC/jeCanvas.h"
#include "GRAPHIC/jeCamera.h"
#include "UTIL/jeData.h"
#include "UTIL/jeEvent.h"
#include "UTIL/jeTime.h"
#include "UTIL/jeMath.h"
#include "jeEntity.h"
#include "jeGroup.h"
#include "jeMain.h"
#include "jePoint.h"
#include "jeUtil.h"
#include "jeWorld.h"