#pragma once

#define this_ptr shared_from_this()

#include "GRAPHIC/PARTICLE/jeEmitterRenderer.h"
#include "GRAPHIC/PARTICLE/jeEmitterType.h"
#include "GRAPHIC/PARTICLE/jeParticle.h"
#include "GRAPHIC/ARMATURE/jeKeyFrame.h"
#include "GRAPHIC/jeGraphic.h"
#include "GRAPHIC/jeImage.h"
#include "GRAPHIC/jeEmitter.h"
#include "GRAPHIC/jeSpritemap.h"
#include "GRAPHIC/jeTilemap.h"
#include "GRAPHIC/jeCanvas.h"
#include "GRAPHIC/jeCamera.h"
#include "UTIL/jeEvent.h"
#include "UTIL/jeTime.h"
#include "UTIL/jeMath.h"
#include "GL/jeModel.h"
#include "GL/jeShader.h"
#include "jeEntity.h"
#include "jeGroup.h"
#include "jeMain.h"
#include "jePoint.h"
#include "jeUtil.h"
#include "jeMain.h"